### ISSUE TITLE
Support for AWS EC2 / Azure VMs

### ISSUE THREAD

**Issue by onuralp** [dhoer/choco-screen-resolution#1]
I just tried choco-screen-resolution on a Windows Server 2016 on an AWS EC2. It didn't work. 

I see your configuration tested on Vagrant and, not sure supports the EC2 or any remote VMs.

If it doesn't already support them, you can take this as a feature request.

**Comment by dhoer** [comment]
I will take a look at this this week. It should have worked out of the box.  I worked with AWS on this originally and this was the solution we came up with to manage resolution without drivers.

**Comment by dhoer** [comment]
I tested this out on Amazon 2012R2 and 2016 AMIs and had no issues.  Can you please provide the error that you are seeing?

**Comment by dhoer** [comment]
I added a terraform example that show how to install chocolatey and screen-resolution via user data: https://github.com/dhoer/terraform_examples/blob/master/choco-selenium-grid/nodes/asg_user_data.tpl

Let me know if that helps...

**Comment by dhoer** [comment]
Closing this because screen resolution was verified working on AWS and no response to request for more info.

**Comment by praveen4463** [comment]
It works perfectly, I tested on an EC2 win 2019. 
@dhoer, thank you very much for this project!
