### ISSUE TITLE
How to get around the fact that password is exposed in cleartext

### ISSUE THREAD

**Issue by ghost** [dhoer/choco-screen-resolution#4]
Hi

This utility has worked wonderfully well for us. We are using Microsoft Windows Server 2019 Datacenter Edition 1809. However, we are unable to use it in production, as our security team has flagged the following as an issue. 

Issue Desc: The autologon feature, while convenient, compromises the physical security of the workstation. Furthermore, it stores the autologin username and password in plaintext in the Windows registry: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon

We were hoping to keep the autologin ON but have the password either stored in an encrypted fashion or have it read from a secret. Is this something that can be explored ? Has anyone else reached out to you with a similar issue ?

**Comment by dhoer** [comment]
While windows version of autologon is insecure: https://support.microsoft.com/en-us/help/324737/how-to-turn-on-automatic-logon-in-windows, the choco autologon is encrypted: https://chocolatey.org/packages/autologon.  So give that a try and let me know how it goes.
